name: logviewer-cicd

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  PROJECT_NAME: ticket-mate-logviewer
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    if: ${{ !startsWith(github.event.head_commit.message, 'version(') }}
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4

      - name: Go 설정
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: DockerHub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: 원격 서버 SSH 연결 및 배포
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}

          script: |
            set -e
            export PATH=$PATH:/usr/local/bin
            
            echo "환경변수 설정"
            PW="${{ secrets.SERVER_PASSWORD }}"
            BRANCH="${{ github.ref_name }}"
            REPO="${{ env.DOCKERHUB_REPO }}"
            PROJECT="${{ env.PROJECT_NAME }}"
            IMAGE="${REPO}/${PROJECT}:${BRANCH}"
            CONTAINER_NAME="${PROJECT}"
            
            echo "Docker 이미지 pull: ${IMAGE}"
            echo "${PW}" | sudo -S docker pull "${IMAGE}"
            
            # 이미 같은 이름의 컨테이너가 있으면 정지 후 삭제
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^${CONTAINER_NAME}\$"; then
              echo "이미 작동중인 컨테이너 정지: ${CONTAINER_NAME}"
              echo "${PW}" | sudo -S docker stop "${CONTAINER_NAME}" || true
              echo "작동중인 컨테이너 삭제: ${CONTAINER_NAME}"
              echo "${PW}" | sudo -S docker rm "${CONTAINER_NAME}" || true
            fi
            
            echo "새로운 컨테이너 시작: ${CONTAINER_NAME}"
            
            echo "${PW}" | sudo -S docker run -d \
              --name "${CONTAINER_NAME}" \
              -p 8888:8080 \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -u 0:0 \
              --restart unless-stopped \
              "${IMAGE}"
            
            echo "컨테이너 배포 완료"